name: when-pull-merged

on:
  pull_request:
    branches: master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: action
      env:
        TEXT_PAYLOAD: |
          :gh-merged2: ${{ github.actor }} merged [${{ github.event.pull_request.base.repo.name }}#${{ github.event.pull_request.number }}] <${{ github.event.pull_request._links.html.href }}|${{ github.event.pull_request.title }}> to `${{ github.event.pull_request.head.label }}` -> `${{ github.event.pull_request.base.label }}`
      if: github.event.pull_request.merged == true
      run: |
        jq -nac --arg msg "$TEXT_PAYLOAD" '{text:$msg}'
